name: Build
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: make release
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: dist/mouselock.dmg
          fail_on_unmatched_files: true
          generate_release_notes: true
